//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedBot.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdvancedBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ascii {
            get {
                object obj = ResourceManager.GetObject("ascii", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] BannerPatterns {
            get {
                object obj = ResourceManager.GetObject("BannerPatterns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] blocks {
            get {
                object obj = ResourceManager.GetObject("blocks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap changelog {
            get {
                object obj = ResourceManager.GetObject("changelog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cmdBlock {
            get {
                object obj = ResourceManager.GetObject("cmdBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coutry {
            get {
                object obj = ResourceManager.GetObject("coutry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap debug_textures_blocks {
            get {
                object obj = ResourceManager.GetObject("debug_textures_blocks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap debug_textures_items {
            get {
                object obj = ResourceManager.GetObject("debug_textures_items", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap discord1 {
            get {
                object obj = ResourceManager.GetObject("discord1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fechar {
            get {
                object obj = ResourceManager.GetObject("fechar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ad,0,0
        ///ae,16,0
        ///af,32,0
        ///ag,48,0
        ///ai,64,0
        ///al,80,0
        ///am,96,0
        ///an,112,0
        ///ao,128,0
        ///ar,144,0
        ///as,160,0
        ///at,176,0
        ///au,192,0
        ///aw,208,0
        ///ax,224,0
        ///az,240,0
        ///ba,0,16
        ///bb,16,16
        ///bd,32,16
        ///be,48,16
        ///bf,64,16
        ///bg,80,16
        ///bh,96,16
        ///bi,112,16
        ///bj,128,16
        ///bm,144,16
        ///bn,160,16
        ///bo,176,16
        ///br,192,16
        ///bs,208,16
        ///bt,224,16
        ///bv,240,16
        ///bw,0,32
        ///by,16,32
        ///bz,32,32
        ///ca,48,32
        ///catalonia,64,32
        ///cc,80,32
        ///cd,96,32
        ///cf,112,32
        ///cg,128,32
        ///ch,144,32
        ///ci,160,32
        ///ck,176,32
        ///cl,192,32
        ///cm,208,32
        ///cn,224,32
        ///co,240,32
        ///cr,0,48
        ///cs,16,48
        ///cu,32,48
        ///cv,48,48
        ///cx,64,48
        ///cy,80,48
        ///cz,96,48
        ///de, [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string flag_map {
            get {
                return ResourceManager.GetString("flag_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_sprite {
            get {
                object obj = ResourceManager.GetObject("flag_sprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_icon {
            get {
                object obj = ResourceManager.GetObject("folder_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap inv_slots {
            get {
                object obj = ResourceManager.GetObject("inv_slots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap item_blocks {
            get {
                object obj = ResourceManager.GetObject("item_blocks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a itemId,itemDamage,textureX,textureY
        ///1,0,0,0
        ///2,0,32,0
        ///3,0,64,0
        ///4,0,96,0
        ///5,0,128,0
        ///5,1,160,0
        ///5,2,192,0
        ///5,3,224,0
        ///5,4,256,0
        ///5,5,288,0
        ///6,0,320,0
        ///6,1,352,0
        ///6,2,384,0
        ///6,3,416,0
        ///6,4,448,0
        ///6,5,480,0
        ///7,0,512,0
        ///8,0,544,0
        ///9,0,576,0
        ///10,0,608,0
        ///11,0,640,0
        ///12,0,672,0
        ///12,1,704,0
        ///13,0,736,0
        ///14,0,768,0
        ///15,0,800,0
        ///16,0,832,0
        ///17,0,864,0
        ///17,1,896,0
        ///17,2,928,0
        ///17,3,960,0
        ///18,0,992,0
        ///18,1,0,32
        ///18,2,32,32
        ///18,3,64,32
        ///19,0,96,32
        ///20,0,128,32
        ///21,0,160,32
        ///22,0,192,32
        ///23,0,224,32
        ///24,0,256,32
        ///24, [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string item_blocks_textures {
            get {
                return ResourceManager.GetString("item_blocks_textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] itemmap_csv {
            get {
                object obj = ResourceManager.GetObject("itemmap_csv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] items {
            get {
                object obj = ResourceManager.GetObject("items", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] materials {
            get {
                object obj = ResourceManager.GetObject("materials", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap minimizar {
            get {
                object obj = ResourceManager.GetObject("minimizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] portals {
            get {
                object obj = ResourceManager.GetObject("portals", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap prefix {
            get {
                object obj = ResourceManager.GetObject("prefix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap proxy {
            get {
                object obj = ResourceManager.GetObject("proxy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] recipes {
            get {
                object obj = ResourceManager.GetObject("recipes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_account_circle_white_18dp {
            get {
                object obj = ResourceManager.GetObject("round_account_circle_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_dns_white_18dp {
            get {
                object obj = ResourceManager.GetObject("round_dns_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_dns_white_18dp1 {
            get {
                object obj = ResourceManager.GetObject("round_dns_white_18dp1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sharp_close_white_18dp {
            get {
                object obj = ResourceManager.GetObject("sharp_close_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] states {
            get {
                object obj = ResourceManager.GetObject("states", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap steve {
            get {
                object obj = ResourceManager.GetObject("steve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] texturemap_csv {
            get {
                object obj = ResourceManager.GetObject("texturemap_csv", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
