using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Runtime.InteropServices;
using System.Reflection;
using System.Diagnostics;

[assembly: Obfuscation(Exclude = false, Feature = "namespace('AdvancedBot.Viewer'):+rename(mode=sequential)")]

#pragma warning disable IDE1006
namespace AdvancedBot.Viewer
{
    public class GL
    {
        public delegate int GenLists(int range);
        public delegate int GetError();
        public delegate void AlphaFunc(int func, float ref_);
        public delegate void Begin(int c);
        public delegate void BindTexture(int target, int texture);
        public delegate void BlendFunc(int sfactor, int dfactor);
        public delegate void BlendFuncSeparate(int srcRGB, int dstRGB, int srcAlpha, int dstAlpha);
        public delegate void CallList(int list);
        public delegate void Clear(int mask);
        public delegate void ClearColor(float red, float green, float blue, float alpha);
        public delegate void Color3f(float r, float g, float b);
        public delegate void Color4f(float r, float g, float b, float a);
        public delegate void ColorPointer(int size, int type, int stride, IntPtr pointer);
        public delegate void DeleteLists(int list, int range);
        public delegate void DeleteTextures(int n, int[] textures);
        public delegate void DepthFunc(int func);
        public delegate void DepthMask(bool flag);
        public delegate void Disable(int cap);
        public delegate void DisableClientState(int array);
        public delegate void DrawArrays(int mode, int first, int count);
        public delegate void Enable(int cap);
        public delegate void EnableClientState(int array);
        public delegate void End();
        public delegate void EndList();
        public delegate void GenTextures(int n, int[] textures);
        public delegate void GetDoublev(int pname, double[] paramss);
        public delegate void GetIntegerv(int pname, int[] paramss);
        public delegate void Hint(int target, int mode);
        public delegate void LineWidth(float width);
        public delegate void LoadIdentity();
        public delegate void MatrixMode(int mode);
        public delegate void NewList(int list, int mode);
        public delegate void Ortho(double left, double right, double bottom, double top, double zNear, double zFar);
        public delegate void PopMatrix();
        public delegate void PolygonMode(int face, int mode);
        public delegate void PushMatrix();
        public delegate void Rotatef(float angle, float x, float y, float z);
        public delegate void Scalef(float x, float y, float z);
        public delegate void ShadeModel(int mode);
        public delegate void TexCoord2f(float x, float y);
        public delegate void TexCoordPointer(int size, int type, int stride, IntPtr pointer);
        public delegate void TexImage2D(int target, int level, int internalformat, int width, int height, int border, int format, int type, IntPtr pixels);
        public delegate void TexSubImage2D(int target, int level, int xoffset, int yoffset, int width, int height, int format, int type, IntPtr pixels);
        public delegate void TexParameterf(int target, int pname, float param);
        public delegate void TexParameteri(int target, int pname, int param);
        public delegate void PixelStorei(int pname, int param);
        public delegate void Translated(double x, double y, double z);
        public delegate void Vertex2f(float x, float y);
        public delegate void Vertex2i(int x, int y);
        public delegate void Vertex3d(double x, double y, double z);
        public delegate void Vertex3f(float x, float y, float z);
        public delegate void VertexPointer(int size, int type, int stride, IntPtr pointer);
        public delegate void Viewport(int x, int y, int width, int height);

        [GLFunc("glAlphaFunc")]          public static AlphaFunc glAlphaFunc;
        [GLFunc("glBegin")]              public static Begin glBegin;
        [GLFunc("glBindTexture")]        public static BindTexture glBindTexture;
        [GLFunc("glBlendFunc")]          public static BlendFunc glBlendFunc;
        [GLFunc("glBlendFuncSeparateEXT", Type = GLFuncType.Extension)]  public static BlendFuncSeparate glBlendFuncSeparate;
        [GLFunc("glCallList")]           public static CallList glCallList;
        [GLFunc("glClear")]              public static Clear glClear;
        [GLFunc("glClearColor")]         public static ClearColor glClearColor;
        [GLFunc("glColor3f")]            public static Color3f glColor3f;
        [GLFunc("glColor4f")]            public static Color4f glColor4f;
        [GLFunc("glColorPointer")]       public static ColorPointer glColorPointer;
        [GLFunc("glDeleteLists")]        public static DeleteLists glDeleteLists;
        [GLFunc("glDeleteTextures")]     public static DeleteTextures glDeleteTextures;
        [GLFunc("glDepthFunc")]          public static DepthFunc glDepthFunc;
        [GLFunc("glDepthMask")]          public static DepthMask glDepthMask;
        [GLFunc("glDisable")]            public static Disable glDisable;
        [GLFunc("glDisableClientState")] public static DisableClientState glDisableClientState;
        [GLFunc("glDrawArrays")]         public static DrawArrays glDrawArrays;
        [GLFunc("glEnable")]             public static Enable glEnable;
        [GLFunc("glEnableClientState")]  public static EnableClientState glEnableClientState;
        [GLFunc("glEnd")]                public static End glEnd;
        [GLFunc("glEndList")]            public static EndList glEndList;
        [GLFunc("glGenLists")]           public static GenLists glGenLists;
        [GLFunc("glGenTextures")]        public static GenTextures glGenTextures;
        [GLFunc("glGetDoublev")]         public static GetDoublev glGetDoublev;
        [GLFunc("glGetError")]           public static GetError glGetError;
        [GLFunc("glGetIntegerv")]        public static GetIntegerv glGetIntegerv;
        [GLFunc("glHint")]               public static Hint glHint;
        [GLFunc("glLineWidth")]          public static LineWidth glLineWidth;
        [GLFunc("glLoadIdentity")]       public static LoadIdentity glLoadIdentity;
        [GLFunc("glMatrixMode")]         public static MatrixMode glMatrixMode;
        [GLFunc("glNewList")]            public static NewList glNewList;
        [GLFunc("glOrtho")]              public static Ortho glOrtho;
        [GLFunc("glPopMatrix")]          public static PopMatrix glPopMatrix;
        [GLFunc("glPolygonMode")]        public static PolygonMode glPolygonMode;
        [GLFunc("glPushMatrix")]         public static PushMatrix glPushMatrix;
        [GLFunc("glRotatef")]            public static Rotatef glRotatef;
        [GLFunc("glScalef")]             public static Scalef glScalef;
        [GLFunc("glShadeModel")]         public static ShadeModel glShadeModel;
        [GLFunc("glTexCoord2f")]         public static TexCoord2f glTexCoord2f;
        [GLFunc("glTexCoordPointer")]    public static TexCoordPointer glTexCoordPointer;
        [GLFunc("glTexImage2D")]         public static TexImage2D glTexImage2D;
        [GLFunc("glTexSubImage2D")]      public static TexSubImage2D glTexSubImage2D;
        [GLFunc("glTexParameterf")]      public static TexParameterf glTexParameterf;
        [GLFunc("glTexParameteri")]      public static TexParameteri glTexParameteri;
        [GLFunc("glPixelStorei")]        public static PixelStorei glPixelStorei;
        [GLFunc("glTranslated")]         public static Translated glTranslated;
        [GLFunc("glVertex2f")]           public static Vertex2f glVertex2f;
        [GLFunc("glVertex2i")]           public static Vertex2i glVertex2i;
        [GLFunc("glVertex3d")]           public static Vertex3d glVertex3d;
        [GLFunc("glVertex3f")]           public static Vertex3f glVertex3f;
        [GLFunc("glVertexPointer")]      public static VertexPointer glVertexPointer;
        [GLFunc("glViewport")]           public static Viewport glViewport;

        public static int glCreateTexture()
        {
            int[] n = new int[1];
            glGenTextures(1, n);
            return n[0];
        }
        public static void glDeleteTexture(int texture)
        {
            glDeleteTextures(1, new[] { texture });
        }
        public static int glGetInteger(int pname)
        {
            int[] p = new int[1];
            glGetIntegerv(pname, p);
            return p[0];
        }


        [DllImport("glu32.dll")] public static extern void gluPerspective(double fovy, double aspect, double zNear, double zFar);
        [DllImport("glu32.dll", CharSet = CharSet.Ansi)] public static extern string gluErrorString(int errorCode);
        [DllImport("glu32.dll")]
        public static extern int gluUnProject(
            double winx, 
            double winy,
            double winz,
            double[] modelMatrix, 
            double[] projMatrix, 
            int[] viewport, 
            out double objx, 
            out double objy, 
            out double objz
        );

        //http://nehe.gamedev.net/tutorial/vertex_buffer_objects/22002/
        //https://raw.githubusercontent.com/mono/tao/master/src/Tao.OpenGl/Gl.cs

        public static bool IsVBOAvailable = false;
        
        [DllImport("opengl32.dll")] public static extern IntPtr wglGetProcAddress(string s);

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode)] private static extern IntPtr LoadLibrary(string lpLibFileName);
        [DllImport("kernel32.dll")] private static extern IntPtr GetProcAddress(IntPtr hModule, string lpProcName);

        [DllImport("opengl32.dll", EntryPoint="glGetString")] private static extern IntPtr _glGetString(int name);

        public static string glGetString(int name)
        {
            return Marshal.PtrToStringAnsi(_glGetString(name));
        }

        public const int GL_ARRAY_BUFFER_ARB    = 0x8892;
        public const int GL_STATIC_DRAW_ARB     = 0x88E4;
        public const int GL_DYNAMIC_DRAW_ARB    = 0x88E8;
        
        public delegate void GenBuffersARB(int n, out int buffers);
        public delegate void DeleteBuffersARB(int n, ref int buffers);
        public delegate void BindBufferARB(int target, int buffer);
        public delegate void BufferDataARB(int target, IntPtr size, IntPtr data, int usage);

        [GLFunc("glGenBuffersARB", Type = GLFuncType.Extension)]    public static GenBuffersARB glGenBuffersARB;
        [GLFunc("glDeleteBuffersARB", Type = GLFuncType.Extension)] public static DeleteBuffersARB glDeleteBuffersARB;
        [GLFunc("glBindBufferARB", Type = GLFuncType.Extension)]    public static BindBufferARB glBindBufferARB;
        [GLFunc("glBufferDataARB", Type = GLFuncType.Extension)]    public static BufferDataARB glBufferDataARB;

        public static string Version { get; private set; }
        private static IntPtr hLibOpenGL = IntPtr.Zero;

        public static void Setup()
        {
            if(hLibOpenGL == IntPtr.Zero) {
                hLibOpenGL = LoadLibrary("opengl32.dll");
            }
            Version = glGetString(GL_VERSION);

            string exts = glGetString(GL_EXTENSIONS);

            IsVBOAvailable = exts.Contains("ARB_vertex_buffer_object");

            //https://www.khronos.org/opengl/wiki/Load_OpenGL_Functions
            foreach (FieldInfo field in typeof(GL).GetFields(BindingFlags.Static | BindingFlags.Public)) {
                var attrib = field.GetCustomAttribute<GLFuncAttribute>();
                if (attrib != null) {
                    IntPtr funcAddr = IntPtr.Zero;
                    switch(attrib.Type) {
                        case GLFuncType.Core: funcAddr = GetProcAddress(hLibOpenGL, attrib.Name); break;
                        case GLFuncType.Extension: funcAddr = wglGetProcAddress(attrib.Name); break;
                        default: throw new InvalidOperationException("Invalid function type");
                    }
                    if (IsValidFunctionPointer(funcAddr)) {
                        field.SetValue(null, Marshal.GetDelegateForFunctionPointer(funcAddr, field.FieldType));
                    } else {
                        Debug.WriteLine("Failed to get " + attrib.Name + " address");
                    }
                }
            }
        }
        private static bool IsValidFunctionPointer(IntPtr addr)
        {
            return addr != (IntPtr)0 &&
                   addr != (IntPtr)1 &&
                   addr != (IntPtr)2 &&
                   addr != (IntPtr)3 &&
                   addr != (IntPtr)(-1);
        }

        public class GLFuncAttribute : Attribute
        {
            public string Name { get; }
            public GLFuncType Type { get; set; } = GLFuncType.Core;

            public GLFuncAttribute(string funcName)
            {
                Name = funcName;
            }
        }
        public enum GLFuncType
        {
            Core,
            Extension
        }

        #region Consts
        public const int GL_ACTIVE_TEXTURE = 0x84E0;
        public const int GL_SHADING_LANGUAGE_VERSION = 0x8B8C;
        public const int GL_2D = 0x600;
        public const int GL_2_BYTES = 0x1407;
        public const int GL_3D = 0x601;
        public const int GL_3D_COLOR = 0x602;
        public const int GL_3D_COLOR_TEXTURE = 0x603;
        public const int GL_3_BYTES = 0x1408;
        public const int GL_4D_COLOR_TEXTURE = 0x604;
        public const int GL_4_BYTES = 0x1409;
        public const int GL_ACCUM = 0x100;
        public const int GL_ACCUM_ALPHA_BITS = 0xD5B;
        public const int GL_ACCUM_BLUE_BITS = 0xD5A;
        public const int GL_ACCUM_BUFFER_BIT = 0x200;
        public const int GL_ACCUM_CLEAR_VALUE = 0xB80;
        public const int GL_ACCUM_GREEN_BITS = 0xD59;
        public const int GL_ACCUM_RED_BITS = 0xD58;
        public const int GL_ACTIVE_ATTRIBUTES = 0x8B89;
        public const int GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = 0x8B8A;
        public const int GL_ACTIVE_UNIFORMS = 0x8B86;
        public const int GL_ACTIVE_UNIFORM_BLOCKS = 0x8A36;
        public const int GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = 0x8A35;
        public const int GL_ACTIVE_UNIFORM_MAX_LENGTH = 0x8B87;
        public const int GL_ADD = 0x104;
        public const int GL_ADD_SIGNED = 0x8574;
        public const int GL_ALIASED_LINE_WIDTH_RANGE = 0x846E;
        public const int GL_ALIASED_POINT_SIZE_RANGE = 0x846D;
        public const int GL_ALL_ATTRIB_BITS = 0xFFFFF;
        public const int GL_ALL_CLIENT_ATTRIB_BITS = -1;
        public const int GL_ALPHA = 0x1906;
        public const int GL_ALPHA12 = 0x803D;
        public const int GL_ALPHA16 = 0x803E;
        public const int GL_ALPHA16F = 0x881C;
        public const int GL_ALPHA16I = 0x8D8A;
        public const int GL_ALPHA16UI = 0x8D78;
        public const int GL_ALPHA32F = 0x8816;
        public const int GL_ALPHA32I = 0x8D84;
        public const int GL_ALPHA32UI = 0x8D72;
        public const int GL_ALPHA4 = 0x803B;
        public const int GL_ALPHA8 = 0x803C;
        public const int GL_ALPHA8I = 0x8D90;
        public const int GL_ALPHA8UI = 0x8D7E;
        public const int GL_ALPHA_BIAS = 0xD1D;
        public const int GL_ALPHA_BITS = 0xD55;
        public const int GL_ALPHA_INTEGER = 0x8D97;
        public const int GL_ALPHA_SCALE = 0xD1C;
        public const int GL_ALPHA_TEST = 0xBC0;
        public const int GL_ALPHA_TEST_FUNC = 0xBC1;
        public const int GL_ALPHA_TEST_REF = 0xBC2;
        public const int GL_ALWAYS = 0x207;
        public const int GL_AMBIENT = 0x1200;
        public const int GL_AMBIENT_AND_DIFFUSE = 0x1602;
        public const int GL_AND = 0x1501;
        public const int GL_AND_INVERTED = 0x1504;
        public const int GL_AND_REVERSE = 0x1502;
        public const int GL_ARRAY_BUFFER = 0x8892;
        public const int GL_ARRAY_BUFFER_BINDING = 0x8894;
        public const int GL_ATTACHED_SHADERS = 0x8B85;
        public const int GL_ATTRIB_STACK_DEPTH = 0xBB0;
        public const int GL_AUTO_NORMAL = 0xD80;
        public const int GL_AUX0 = 0x409;
        public const int GL_AUX1 = 0x40A;
        public const int GL_AUX2 = 0x40B;
        public const int GL_AUX3 = 0x40C;
        public const int GL_AUX_BUFFERS = 0xC00;
        public const int GL_BACK = 0x405;
        public const int GL_BACK_LEFT = 0x402;
        public const int GL_BACK_RIGHT = 0x403;
        public const int GL_BGR = 0x80E0;
        public const int GL_BGRA = 0x80E1;
        public const int GL_BGRA_INTEGER = 0x8D9B;
        public const int GL_BGR_INTEGER = 0x8D9A;
        public const int GL_BITMAP = 0x1A00;
        public const int GL_BITMAP_TOKEN = 0x704;
        public const int GL_BLEND = 0xBE2;
        public const int GL_BLEND_COLOR = 0x8005;
        public const int GL_BLEND_DST = 0xBE0;
        public const int GL_BLEND_DST_ALPHA = 0x80CA;
        public const int GL_BLEND_DST_RGB = 0x80C8;
        public const int GL_BLEND_EQUATION = 0x8009;
        public const int GL_BLEND_EQUATION_ALPHA = 0x883D;
        public const int GL_BLEND_EQUATION_RGB = 0x8009;
        public const int GL_BLEND_SRC = 0xBE1;
        public const int GL_BLEND_SRC_ALPHA = 0x80CB;
        public const int GL_BLEND_SRC_RGB = 0x80C9;
        public const int GL_BLUE = 0x1905;
        public const int GL_BLUE_BIAS = 0xD1B;
        public const int GL_BLUE_BITS = 0xD54;
        public const int GL_BLUE_INTEGER = 0x8D96;
        public const int GL_BLUE_SCALE = 0xD1A;
        public const int GL_BOOL = 0x8B56;
        public const int GL_BOOL_VEC2 = 0x8B57;
        public const int GL_BOOL_VEC3 = 0x8B58;
        public const int GL_BOOL_VEC4 = 0x8B59;
        public const int GL_BUFFER_ACCESS = 0x88BB;
        public const int GL_BUFFER_ACCESS_FLAGS = 0x911F;
        public const int GL_BUFFER_MAPPED = 0x88BC;
        public const int GL_BUFFER_MAP_LENGTH = 0x9120;
        public const int GL_BUFFER_MAP_OFFSET = 0x9121;
        public const int GL_BUFFER_MAP_POINTER = 0x88BD;
        public const int GL_BUFFER_SIZE = 0x8764;
        public const int GL_BUFFER_USAGE = 0x8765;
        public const int GL_BYTE = 0x1400;
        public const int GL_C3F_V3F = 0x2A24;
        public const int GL_C4F_N3F_V3F = 0x2A26;
        public const int GL_C4UB_V2F = 0x2A22;
        public const int GL_C4UB_V3F = 0x2A23;
        public const int GL_CCW = 0x901;
        public const int GL_CLAMP = 0x2900;
        public const int GL_CLAMP_FRAGMENT_COLOR = 0x891B;
        public const int GL_CLAMP_READ_COLOR = 0x891C;
        public const int GL_CLAMP_TO_BORDER = 0x812D;
        public const int GL_CLAMP_TO_EDGE = 0x812F;
        public const int GL_CLAMP_VERTEX_COLOR = 0x891A;
        public const int GL_CLEAR = 0x1500;
        public const int GL_CLIENT_ACTIVE_TEXTURE = 0x84E1;
        public const int GL_CLIENT_ATTRIB_STACK_DEPTH = 0xBB1;
        public const int GL_CLIENT_PIXEL_STORE_BIT = 0x01;
        public const int GL_CLIENT_VERTEX_ARRAY_BIT = 0x02;
        public const int GL_CLIP_DISTANCE0 = 0x3000;
        public const int GL_CLIP_DISTANCE1 = 0x3001;
        public const int GL_CLIP_DISTANCE2 = 0x3002;
        public const int GL_CLIP_DISTANCE3 = 0x3003;
        public const int GL_CLIP_DISTANCE4 = 0x3004;
        public const int GL_CLIP_DISTANCE5 = 0x3005;
        public const int GL_CLIP_DISTANCE6 = 0x3006;
        public const int GL_CLIP_DISTANCE7 = 0x3007;
        public const int GL_CLIP_PLANE0 = 0x3000;
        public const int GL_CLIP_PLANE1 = 0x3001;
        public const int GL_CLIP_PLANE2 = 0x3002;
        public const int GL_CLIP_PLANE3 = 0x3003;
        public const int GL_CLIP_PLANE4 = 0x3004;
        public const int GL_CLIP_PLANE5 = 0x3005;
        public const int GL_COEFF = 0xA00;
        public const int GL_COLOR = 0x1800;
        public const int GL_COLOR_ARRAY = 0x8076;
        public const int GL_COLOR_ARRAY_BUFFER_BINDING = 0x8898;
        public const int GL_COLOR_ARRAY_POINTER = 0x8090;
        public const int GL_COLOR_ARRAY_SIZE = 0x8081;
        public const int GL_COLOR_ARRAY_STRIDE = 0x8083;
        public const int GL_COLOR_ARRAY_TYPE = 0x8082;
        public const int GL_COLOR_ATTACHMENT0 = 0x8CE0;
        public const int GL_COLOR_ATTACHMENT1 = 0x8CE1;
        public const int GL_COLOR_ATTACHMENT10 = 0x8CEA;
        public const int GL_COLOR_ATTACHMENT11 = 0x8CEB;
        public const int GL_COLOR_ATTACHMENT12 = 0x8CEC;
        public const int GL_COLOR_ATTACHMENT13 = 0x8CED;
        public const int GL_COLOR_ATTACHMENT14 = 0x8CEE;
        public const int GL_COLOR_ATTACHMENT15 = 0x8CEF;
        public const int GL_COLOR_ATTACHMENT2 = 0x8CE2;
        public const int GL_COLOR_ATTACHMENT3 = 0x8CE3;
        public const int GL_COLOR_ATTACHMENT4 = 0x8CE4;
        public const int GL_COLOR_ATTACHMENT5 = 0x8CE5;
        public const int GL_COLOR_ATTACHMENT6 = 0x8CE6;
        public const int GL_COLOR_ATTACHMENT7 = 0x8CE7;
        public const int GL_COLOR_ATTACHMENT8 = 0x8CE8;
        public const int GL_COLOR_ATTACHMENT9 = 0x8CE9;
        public const int GL_COLOR_BUFFER_BIT = 0x4000;
        public const int GL_COLOR_CLEAR_VALUE = 0xC22;
        public const int GL_COLOR_INDEX = 0x1900;
        public const int GL_COLOR_INDEXES = 0x1603;
        public const int GL_COLOR_LOGIC_OP = 0xBF2;
        public const int GL_COLOR_MATERIAL = 0xB57;
        public const int GL_COLOR_MATERIAL_FACE = 0xB55;
        public const int GL_COLOR_MATERIAL_PARAMETER = 0xB56;
        public const int GL_COLOR_SUM = 0x8458;
        public const int GL_COLOR_WRITEMASK = 0xC23;
        public const int GL_COMBINE = 0x8570;
        public const int GL_COMBINE_ALPHA = 0x8572;
        public const int GL_COMBINE_RGB = 0x8571;
        public const int GL_COMPARE_REF_DEPTH_TO_TEXTURE = 0x884E;
        public const int GL_COMPARE_REF_TO_TEXTURE = 0x884E;
        public const int GL_COMPARE_R_TO_TEXTURE = 0x884E;
        public const int GL_COMPILE = 0x1300;
        public const int GL_COMPILE_AND_EXECUTE = 0x1301;
        public const int GL_COMPILE_STATUS = 0x8B81;
        public const int GL_COMPRESSED_ALPHA = 0x84E9;
        public const int GL_COMPRESSED_INTENSITY = 0x84EC;
        public const int GL_COMPRESSED_LUMINANCE = 0x84EA;
        public const int GL_COMPRESSED_LUMINANCE_ALPHA = 0x84EB;
        public const int GL_COMPRESSED_RED = 0x8225;
        public const int GL_COMPRESSED_RED_RGTC1 = 0x8DBB;
        public const int GL_COMPRESSED_RG = 0x8226;
        public const int GL_COMPRESSED_RGB = 0x84ED;
        public const int GL_COMPRESSED_RGBA = 0x84EE;
        public const int GL_COMPRESSED_RG_RGTC2 = 0x8DBD;
        public const int GL_COMPRESSED_SIGNED_RED_RGTC1 = 0x8DBC;
        public const int GL_COMPRESSED_SIGNED_RG_RGTC2 = 0x8DBE;
        public const int GL_COMPRESSED_SLUMINANCE = 0x8C4A;
        public const int GL_COMPRESSED_SLUMINANCE_ALPHA = 0x8C4B;
        public const int GL_COMPRESSED_SRGB = 0x8C48;
        public const int GL_COMPRESSED_SRGB_ALPHA = 0x8C49;
        public const int GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3;
        public const int GL_CONSTANT = 0x8576;
        public const int GL_CONSTANT_ALPHA = 0x8003;
        public const int GL_CONSTANT_ATTENUATION = 0x1207;
        public const int GL_CONSTANT_COLOR = 0x8001;
        public const int GL_CONTEXT_FLAGS = 0x821E;
        public const int GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT = 0x01;
        public const int GL_COORD_REPLACE = 0x8862;
        public const int GL_COPY = 0x1503;
        public const int GL_COPY_INVERTED = 0x150C;
        public const int GL_COPY_PIXEL_TOKEN = 0x706;
        public const int GL_COPY_READ_BUFFER = 0x8F36;
        public const int GL_COPY_READ_BUFFER_BINDING = 0x8F36;
        public const int GL_COPY_WRITE_BUFFER = 0x8F37;
        public const int GL_COPY_WRITE_BUFFER_BINDING = 0x8F37;
        public const int GL_CULL_FACE = 0xB44;
        public const int GL_CULL_FACE_MODE = 0xB45;
        public const int GL_CURRENT_BIT = 0x01;
        public const int GL_CURRENT_COLOR = 0xB00;
        public const int GL_CURRENT_FOG_COORD = 0x8453;
        public const int GL_CURRENT_FOG_COORDINATE = 0x8453;
        public const int GL_CURRENT_INDEX = 0xB01;
        public const int GL_CURRENT_NORMAL = 0xB02;
        public const int GL_CURRENT_PROGRAM = 0x8B8D;
        public const int GL_CURRENT_QUERY = 0x8865;
        public const int GL_CURRENT_RASTER_COLOR = 0xB04;
        public const int GL_CURRENT_RASTER_DISTANCE = 0xB09;
        public const int GL_CURRENT_RASTER_INDEX = 0xB05;
        public const int GL_CURRENT_RASTER_POSITION = 0xB07;
        public const int GL_CURRENT_RASTER_POSITION_VALID = 0xB08;
        public const int GL_CURRENT_RASTER_SECONDARY_COLOR = 0x845F;
        public const int GL_CURRENT_RASTER_TEXTURE_COORDS = 0xB06;
        public const int GL_CURRENT_SECONDARY_COLOR = 0x8459;
        public const int GL_CURRENT_TEXTURE_COORDS = 0xB03;
        public const int GL_CURRENT_VERTEX_ATTRIB = 0x8626;
        public const int GL_CW = 0x900;
        public const int GL_DECAL = 0x2101;
        public const int GL_DECR = 0x1E03;
        public const int GL_DECR_WRAP = 0x8508;
        public const int GL_DELETE_STATUS = 0x8B80;
        public const int GL_DEPTH = 0x1801;
        public const int GL_DEPTH24_STENCIL8 = 0x88F0;
        public const int GL_DEPTH32F_STENCIL8 = 0x8CAD;
        public const int GL_DEPTH_ATTACHMENT = 0x8D00;
        public const int GL_DEPTH_BIAS = 0xD1F;
        public const int GL_DEPTH_BITS = 0xD56;
        public const int GL_DEPTH_BUFFER = 0x8223;
        public const int GL_DEPTH_BUFFER_BIT = 0x100;
        public const int GL_DEPTH_CLEAR_VALUE = 0xB73;
        public const int GL_DEPTH_COMPONENT = 0x1902;
        public const int GL_DEPTH_COMPONENT16 = 0x81A5;
        public const int GL_DEPTH_COMPONENT24 = 0x81A6;
        public const int GL_DEPTH_COMPONENT32 = 0x81A7;
        public const int GL_DEPTH_COMPONENT32F = 0x8CAC;
        public const int GL_DEPTH_FUNC = 0xB74;
        public const int GL_DEPTH_RANGE = 0xB70;
        public const int GL_DEPTH_SCALE = 0xD1E;
        public const int GL_DEPTH_STENCIL = 0x84F9;
        public const int GL_DEPTH_STENCIL_ATTACHMENT = 0x821A;
        public const int GL_DEPTH_TEST = 0xB71;
        public const int GL_DEPTH_TEXTURE_MODE = 0x884B;
        public const int GL_DEPTH_WRITEMASK = 0xB72;
        public const int GL_DIFFUSE = 0x1201;
        public const int GL_DITHER = 0xBD0;
        public const int GL_DOMAIN = 0xA02;
        public const int GL_DONT_CARE = 0x1100;
        public const int GL_DOT3_RGB = 0x86AE;
        public const int GL_DOT3_RGBA = 0x86AF;
        public const int GL_DOUBLE = 0x140A;
        public const int GL_DOUBLEBUFFER = 0xC32;
        public const int GL_DRAW_BUFFER = 0xC01;
        public const int GL_DRAW_BUFFER0 = 0x8825;
        public const int GL_DRAW_BUFFER1 = 0x8826;
        public const int GL_DRAW_BUFFER10 = 0x882F;
        public const int GL_DRAW_BUFFER11 = 0x8830;
        public const int GL_DRAW_BUFFER12 = 0x8831;
        public const int GL_DRAW_BUFFER13 = 0x8832;
        public const int GL_DRAW_BUFFER14 = 0x8833;
        public const int GL_DRAW_BUFFER15 = 0x8834;
        public const int GL_DRAW_BUFFER2 = 0x8827;
        public const int GL_DRAW_BUFFER3 = 0x8828;
        public const int GL_DRAW_BUFFER4 = 0x8829;
        public const int GL_DRAW_BUFFER5 = 0x882A;
        public const int GL_DRAW_BUFFER6 = 0x882B;
        public const int GL_DRAW_BUFFER7 = 0x882C;
        public const int GL_DRAW_BUFFER8 = 0x882D;
        public const int GL_DRAW_BUFFER9 = 0x882E;
        public const int GL_DRAW_FRAMEBUFFER = 0x8CA9;
        public const int GL_DRAW_FRAMEBUFFER_BINDING = 0x8CA6;
        public const int GL_DRAW_PIXEL_TOKEN = 0x705;
        public const int GL_DST_ALPHA = 0x304;
        public const int GL_DST_COLOR = 0x306;
        public const int GL_DYNAMIC_COPY = 0x88EA;
        public const int GL_DYNAMIC_DRAW = 0x88E8;
        public const int GL_DYNAMIC_READ = 0x88E9;
        public const int GL_EDGE_FLAG = 0xB43;
        public const int GL_EDGE_FLAG_ARRAY = 0x8079;
        public const int GL_EDGE_FLAG_ARRAY_BUFFER_BINDING = 0x889B;
        public const int GL_EDGE_FLAG_ARRAY_POINTER = 0x8093;
        public const int GL_EDGE_FLAG_ARRAY_STRIDE = 0x808C;
        public const int GL_ELEMENT_ARRAY_BUFFER = 0x8893;
        public const int GL_ELEMENT_ARRAY_BUFFER_BINDING = 0x8895;
        public const int GL_EMISSION = 0x1600;
        public const int GL_ENABLE_BIT = 0x2000;
        public const int GL_EQUAL = 0x202;
        public const int GL_EQUIV = 0x1509;
        public const int GL_EVAL_BIT = 0x10000;
        public const int GL_EXP = 0x800;
        public const int GL_EXP2 = 0x801;
        public const int GL_EXTENSIONS = 0x1F03;
        public const int GL_EYE_LINEAR = 0x2400;
        public const int GL_EYE_PLANE = 0x2502;
        public const int GL_FALSE = 0x00;
        public const int GL_FASTEST = 0x1101;
        public const int GL_FEEDBACK = 0x1C01;
        public const int GL_FEEDBACK_BUFFER_POINTER = 0xDF0;
        public const int GL_FEEDBACK_BUFFER_SIZE = 0xDF1;
        public const int GL_FEEDBACK_BUFFER_TYPE = 0xDF2;
        public const int GL_FILL = 0x1B02;
        public const int GL_FIXED_ONLY = 0x891D;
        public const int GL_FLAT = 0x1D00;
        public const int GL_FLOAT = 0x1406;
        public const int GL_FLOAT_32_UNSIGNED_INT_24_8_REV = 0x8DAD;
        public const int GL_FLOAT_MAT2 = 0x8B5A;
        public const int GL_FLOAT_MAT2x3 = 0x8B65;
        public const int GL_FLOAT_MAT2x4 = 0x8B66;
        public const int GL_FLOAT_MAT3 = 0x8B5B;
        public const int GL_FLOAT_MAT3x2 = 0x8B67;
        public const int GL_FLOAT_MAT3x4 = 0x8B68;
        public const int GL_FLOAT_MAT4 = 0x8B5C;
        public const int GL_FLOAT_MAT4x2 = 0x8B69;
        public const int GL_FLOAT_MAT4x3 = 0x8B6A;
        public const int GL_FLOAT_VEC2 = 0x8B50;
        public const int GL_FLOAT_VEC3 = 0x8B51;
        public const int GL_FLOAT_VEC4 = 0x8B52;
        public const int GL_FOG = 0xB60;
        public const int GL_FOG_BIT = 0x80;
        public const int GL_FOG_COLOR = 0xB66;
        public const int GL_FOG_COORD = 0x8451;
        public const int GL_FOG_COORDINATE = 0x8451;
        public const int GL_FOG_COORDINATE_ARRAY = 0x8457;
        public const int GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING = 0x889D;
        public const int GL_FOG_COORDINATE_ARRAY_POINTER = 0x8456;
        public const int GL_FOG_COORDINATE_ARRAY_STRIDE = 0x8455;
        public const int GL_FOG_COORDINATE_ARRAY_TYPE = 0x8454;
        public const int GL_FOG_COORDINATE_SOURCE = 0x8450;
        public const int GL_FOG_COORD_ARRAY = 0x8457;
        public const int GL_FOG_COORD_ARRAY_BUFFER_BINDING = 0x889D;
        public const int GL_FOG_COORD_ARRAY_POINTER = 0x8456;
        public const int GL_FOG_COORD_ARRAY_STRIDE = 0x8455;
        public const int GL_FOG_COORD_ARRAY_TYPE = 0x8454;
        public const int GL_FOG_COORD_SRC = 0x8450;
        public const int GL_FOG_DENSITY = 0xB62;
        public const int GL_FOG_END = 0xB64;
        public const int GL_FOG_HINT = 0xC54;
        public const int GL_FOG_INDEX = 0xB61;
        public const int GL_FOG_MODE = 0xB65;
        public const int GL_FOG_START = 0xB63;
        public const int GL_FRAGMENT_DEPTH = 0x8452;
        public const int GL_FRAGMENT_SHADER = 0x8B30;
        public const int GL_FRAGMENT_SHADER_DERIVATIVE_HINT = 0x8B8B;
        public const int GL_FRAMEBUFFER = 0x8D40;
        public const int GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x8215;
        public const int GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x8214;
        public const int GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x8210;
        public const int GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x8211;
        public const int GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x8216;
        public const int GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x8213;
        public const int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8CD1;
        public const int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8CD0;
        public const int GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x8212;
        public const int GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x8217;
        public const int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0x8CD3;
        public const int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x8CD4;
        public const int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8CD2;
        public const int GL_FRAMEBUFFER_BINDING = 0x8CA6;
        public const int GL_FRAMEBUFFER_COMPLETE = 0x8CD5;
        public const int GL_FRAMEBUFFER_DEFAULT = 0x8218;
        public const int GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0x8CD6;
        public const int GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = 0x8CDB;
        public const int GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0x8CD7;
        public const int GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x8D56;
        public const int GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = 0x8CDC;
        public const int GL_FRAMEBUFFER_SRGB = 0x8DB9;
        public const int GL_FRAMEBUFFER_SRGB_CAPABLE = 0x8DBA;
        public const int GL_FRAMEBUFFER_UNDEFINED = 0x8219;
        public const int GL_FRAMEBUFFER_UNSUPPORTED = 0x8CDD;
        public const int GL_FRONT = 0x404;
        public const int GL_FRONT_AND_BACK = 0x408;
        public const int GL_FRONT_FACE = 0xB46;
        public const int GL_FRONT_LEFT = 0x400;
        public const int GL_FRONT_RIGHT = 0x401;
        public const int GL_FUNC_ADD = 0x8006;
        public const int GL_FUNC_REVERSE_SUBTRACT = 0x800B;
        public const int GL_FUNC_SUBTRACT = 0x800A;
        public const int GL_GENERATE_MIPMAP = 0x8191;
        public const int GL_GENERATE_MIPMAP_HINT = 0x8192;
        public const int GL_GEQUAL = 0x206;
        public const int GL_GREATER = 0x204;
        public const int GL_GREEN = 0x1904;
        public const int GL_GREEN_BIAS = 0xD19;
        public const int GL_GREEN_BITS = 0xD53;
        public const int GL_GREEN_INTEGER = 0x8D95;
        public const int GL_GREEN_SCALE = 0xD18;
        public const int GL_HALF_FLOAT = 0x140B;
        public const int GL_HINT_BIT = 0x8000;
        public const int GL_INCR = 0x1E02;
        public const int GL_INCR_WRAP = 0x8507;
        public const int GL_INDEX = 0x8222;
        public const int GL_INDEX_ARRAY = 0x8077;
        public const int GL_INDEX_ARRAY_BUFFER_BINDING = 0x8899;
        public const int GL_INDEX_ARRAY_POINTER = 0x8091;
        public const int GL_INDEX_ARRAY_STRIDE = 0x8086;
        public const int GL_INDEX_ARRAY_TYPE = 0x8085;
        public const int GL_INDEX_BITS = 0xD51;
        public const int GL_INDEX_CLEAR_VALUE = 0xC20;
        public const int GL_INDEX_LOGIC_OP = 0xBF1;
        public const int GL_INDEX_MODE = 0xC30;
        public const int GL_INDEX_OFFSET = 0xD13;
        public const int GL_INDEX_SHIFT = 0xD12;
        public const int GL_INDEX_WRITEMASK = 0xC21;
        public const int GL_INFO_LOG_LENGTH = 0x8B84;
        public const int GL_INT = 0x1404;
        public const int GL_INTENSITY = 0x8049;
        public const int GL_INTENSITY12 = 0x804C;
        public const int GL_INTENSITY16 = 0x804D;
        public const int GL_INTENSITY4 = 0x804A;
        public const int GL_INTENSITY8 = 0x804B;
        public const int GL_INTERLEAVED_ATTRIBS = 0x8C8C;
        public const int GL_INTERPOLATE = 0x8575;
        public const int GL_INT_SAMPLER_1D = 0x8DC9;
        public const int GL_INT_SAMPLER_1D_ARRAY = 0x8DCE;
        public const int GL_INT_SAMPLER_2D = 0x8DCA;
        public const int GL_INT_SAMPLER_2D_ARRAY = 0x8DCF;
        public const int GL_INT_SAMPLER_2D_RECT = 0x8DCD;
        public const int GL_INT_SAMPLER_3D = 0x8DCB;
        public const int GL_INT_SAMPLER_BUFFER = 0x8DD0;
        public const int GL_INT_SAMPLER_CUBE = 0x8DCC;
        public const int GL_INT_VEC2 = 0x8B53;
        public const int GL_INT_VEC3 = 0x8B54;
        public const int GL_INT_VEC4 = 0x8B55;
        public const int GL_INVALID_ENUM = 0x500;
        public const int GL_INVALID_FRAMEBUFFER_OPERATION = 0x506;
        public const int GL_INVALID_INDEX = -1;
        public const int GL_INVALID_OPERATION = 0x502;
        public const int GL_INVALID_VALUE = 0x501;
        public const int GL_INVERT = 0x150A;
        public const int GL_KEEP = 0x1E00;
        public const int GL_LEFT = 0x406;
        public const int GL_LEQUAL = 0x203;
        public const int GL_LESS = 0x201;
        public const int GL_LIGHT0 = 0x4000;
        public const int GL_LIGHT1 = 0x4001;
        public const int GL_LIGHT2 = 0x4002;
        public const int GL_LIGHT3 = 0x4003;
        public const int GL_LIGHT4 = 0x4004;
        public const int GL_LIGHT5 = 0x4005;
        public const int GL_LIGHT6 = 0x4006;
        public const int GL_LIGHT7 = 0x4007;
        public const int GL_LIGHTING = 0xB50;
        public const int GL_LIGHTING_BIT = 0x40;
        public const int GL_LIGHT_MODEL_AMBIENT = 0xB53;
        public const int GL_LIGHT_MODEL_COLOR_CONTROL = 0x81F8;
        public const int GL_LIGHT_MODEL_LOCAL_VIEWER = 0xB51;
        public const int GL_LIGHT_MODEL_TWO_SIDE = 0xB52;
        public const int GL_LINE = 0x1B01;
        public const int GL_LINEAR = 0x2601;
        public const int GL_LINEAR_ATTENUATION = 0x1208;
        public const int GL_LINEAR_MIPMAP_LINEAR = 0x2703;
        public const int GL_LINEAR_MIPMAP_NEAREST = 0x2701;
        public const int GL_LINES = 0x01;
        public const int GL_LINE_BIT = 0x04;
        public const int GL_LINE_LOOP = 0x02;
        public const int GL_LINE_RESET_TOKEN = 0x707;
        public const int GL_LINE_SMOOTH = 0xB20;
        public const int GL_LINE_SMOOTH_HINT = 0xC52;
        public const int GL_LINE_STIPPLE = 0xB24;
        public const int GL_LINE_STIPPLE_PATTERN = 0xB25;
        public const int GL_LINE_STIPPLE_REPEAT = 0xB26;
        public const int GL_LINE_STRIP = 0x03;
        public const int GL_LINE_TOKEN = 0x702;
        public const int GL_LINE_WIDTH = 0xB21;
        public const int GL_LINE_WIDTH_GRANULARITY = 0xB23;
        public const int GL_LINE_WIDTH_RANGE = 0xB22;
        public const int GL_LINK_STATUS = 0x8B82;
        public const int GL_LIST_BASE = 0xB32;
        public const int GL_LIST_BIT = 0x20000;
        public const int GL_LIST_INDEX = 0xB33;
        public const int GL_LIST_MODE = 0xB30;
        public const int GL_LOAD = 0x101;
        public const int GL_LOGIC_OP = 0xBF1;
        public const int GL_LOGIC_OP_MODE = 0xBF0;
        public const int GL_LOWER_LEFT = 0x8CA1;
        public const int GL_LUMINANCE = 0x1909;
        public const int GL_LUMINANCE12 = 0x8041;
        public const int GL_LUMINANCE12_ALPHA12 = 0x8047;
        public const int GL_LUMINANCE12_ALPHA4 = 0x8046;
        public const int GL_LUMINANCE16 = 0x8042;
        public const int GL_LUMINANCE16_ALPHA16 = 0x8048;
        public const int GL_LUMINANCE4 = 0x803F;
        public const int GL_LUMINANCE4_ALPHA4 = 0x8043;
        public const int GL_LUMINANCE6_ALPHA2 = 0x8044;
        public const int GL_LUMINANCE8 = 0x8040;
        public const int GL_LUMINANCE8_ALPHA8 = 0x8045;
        public const int GL_LUMINANCE_ALPHA = 0x190A;
        public const int GL_MAJOR_VERSION = 0x821B;
        public const int GL_MAP1_COLOR_4 = 0xD90;
        public const int GL_MAP1_GRID_DOMAIN = 0xDD0;
        public const int GL_MAP1_GRID_SEGMENTS = 0xDD1;
        public const int GL_MAP1_INDEX = 0xD91;
        public const int GL_MAP1_NORMAL = 0xD92;
        public const int GL_MAP1_TEXTURE_COORD_1 = 0xD93;
        public const int GL_MAP1_TEXTURE_COORD_2 = 0xD94;
        public const int GL_MAP1_TEXTURE_COORD_3 = 0xD95;
        public const int GL_MAP1_TEXTURE_COORD_4 = 0xD96;
        public const int GL_MAP1_VERTEX_3 = 0xD97;
        public const int GL_MAP1_VERTEX_4 = 0xD98;
        public const int GL_MAP2_COLOR_4 = 0xDB0;
        public const int GL_MAP2_GRID_DOMAIN = 0xDD2;
        public const int GL_MAP2_GRID_SEGMENTS = 0xDD3;
        public const int GL_MAP2_INDEX = 0xDB1;
        public const int GL_MAP2_NORMAL = 0xDB2;
        public const int GL_MAP2_TEXTURE_COORD_1 = 0xDB3;
        public const int GL_MAP2_TEXTURE_COORD_2 = 0xDB4;
        public const int GL_MAP2_TEXTURE_COORD_3 = 0xDB5;
        public const int GL_MAP2_TEXTURE_COORD_4 = 0xDB6;
        public const int GL_MAP2_VERTEX_3 = 0xDB7;
        public const int GL_MAP2_VERTEX_4 = 0xDB8;
        public const int GL_MAP_COLOR = 0xD10;
        public const int GL_MAP_FLUSH_EXPLICIT_BIT = 0x10;
        public const int GL_MAP_INVALIDATE_BUFFER_BIT = 0x08;
        public const int GL_MAP_INVALIDATE_RANGE_BIT = 0x04;
        public const int GL_MAP_READ_BIT = 0x01;
        public const int GL_MAP_STENCIL = 0xD11;
        public const int GL_MAP_UNSYNCHRONIZED_BIT = 0x20;
        public const int GL_MAP_WRITE_BIT = 0x02;
        public const int GL_MATRIX_MODE = 0xBA0;
        public const int GL_MAX = 0x8008;
        public const int GL_MAX_3D_TEXTURE_SIZE = 0x8073;
        public const int GL_MAX_ARRAY_TEXTURE_LAYERS = 0x88FF;
        public const int GL_MAX_ATTRIB_STACK_DEPTH = 0xD35;
        public const int GL_MAX_CLIENT_ATTRIB_STACK_DEPTH = 0xD3B;
        public const int GL_MAX_CLIP_DISTANCES = 0xD32;
        public const int GL_MAX_CLIP_PLANES = 0xD32;
        public const int GL_MAX_COLOR_ATTACHMENTS = 0x8CDF;
        public const int GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = 0x8A33;
        public const int GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS = 0x8A32;
        public const int GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D;
        public const int GL_MAX_COMBINED_UNIFORM_BLOCKS = 0x8A2E;
        public const int GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = 0x8A31;
        public const int GL_MAX_CUBE_MAP_TEXTURE_SIZE = 0x851C;
        public const int GL_MAX_DRAW_BUFFERS = 0x8824;
        public const int GL_MAX_ELEMENTS_INDICES = 0x80E9;
        public const int GL_MAX_ELEMENTS_VERTICES = 0x80E8;
        public const int GL_MAX_EVAL_ORDER = 0xD30;
        public const int GL_MAX_FRAGMENT_UNIFORM_BLOCKS = 0x8A2D;
        public const int GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49;
        public const int GL_MAX_GEOMETRY_UNIFORM_BLOCKS = 0x8A2C;
        public const int GL_MAX_LIGHTS = 0xD31;
        public const int GL_MAX_LIST_NESTING = 0xB31;
        public const int GL_MAX_MODELVIEW_STACK_DEPTH = 0xD36;
        public const int GL_MAX_NAME_STACK_DEPTH = 0xD37;
        public const int GL_MAX_PIXEL_MAP_TABLE = 0xD34;
        public const int GL_MAX_PROGRAM_TEXEL_OFFSET = 0x8905;
        public const int GL_MAX_PROJECTION_STACK_DEPTH = 0xD38;
        public const int GL_MAX_RECTANGLE_TEXTURE_SIZE = 0x84F8;
        public const int GL_MAX_RENDERBUFFER_SIZE = 0x84E8;
        public const int GL_MAX_SAMPLES = 0x8D57;
        public const int GL_MAX_TEXTURE_BUFFER_SIZE = 0x8C2B;
        public const int GL_MAX_TEXTURE_COORDS = 0x8871;
        public const int GL_MAX_TEXTURE_IMAGE_UNITS = 0x8872;
        public const int GL_MAX_TEXTURE_LOD_BIAS = 0x84FD;
        public const int GL_MAX_TEXTURE_SIZE = 0xD33;
        public const int GL_MAX_TEXTURE_STACK_DEPTH = 0xD39;
        public const int GL_MAX_TEXTURE_UNITS = 0x84E2;
        public const int GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 0x8C8A;
        public const int GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 0x8C8B;
        public const int GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 0x8C80;
        public const int GL_MAX_UNIFORM_BLOCK_SIZE = 0x8A30;
        public const int GL_MAX_UNIFORM_BUFFER_BINDINGS = 0x8A2F;
        public const int GL_MAX_VARYING_COMPONENTS = 0x8B4B;
        public const int GL_MAX_VARYING_FLOATS = 0x8B4B;
        public const int GL_MAX_VERTEX_ATTRIBS = 0x8869;
        public const int GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0x8B4C;
        public const int GL_MAX_VERTEX_UNIFORM_BLOCKS = 0x8A2B;
        public const int GL_MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A;
        public const int GL_MAX_VIEWPORT_DIMS = 0xD3A;
        public const int GL_MIN = 0x8007;
        public const int GL_MINOR_VERSION = 0x821C;
        public const int GL_MIN_PROGRAM_TEXEL_OFFSET = 0x8904;
        public const int GL_MIRRORED_REPEAT = 0x8370;
        public const int GL_MODELVIEW = 0x1700;
        public const int GL_MODELVIEW_MATRIX = 0xBA6;
        public const int GL_MODELVIEW_STACK_DEPTH = 0xBA3;
        public const int GL_MODULATE = 0x2100;
        public const int GL_MULT = 0x103;
        public const int GL_MULTISAMPLE = 0x809D;
        public const int GL_MULTISAMPLE_BIT = 0x20000000;
        public const int GL_N3F_V3F = 0x2A25;
        public const int GL_NAME_STACK_DEPTH = 0xD70;
        public const int GL_NAND = 0x150E;
        public const int GL_NEAREST = 0x2600;
        public const int GL_NEAREST_MIPMAP_LINEAR = 0x2702;
        public const int GL_NEAREST_MIPMAP_NEAREST = 0x2700;
        public const int GL_NEVER = 0x200;
        public const int GL_NICEST = 0x1102;
        public const int GL_NONE = 0x00;
        public const int GL_NOOP = 0x1505;
        public const int GL_NOR = 0x1508;
        public const int GL_NORMALIZE = 0xBA1;
        public const int GL_NORMAL_ARRAY = 0x8075;
        public const int GL_NORMAL_ARRAY_BUFFER_BINDING = 0x8897;
        public const int GL_NORMAL_ARRAY_POINTER = 0x808F;
        public const int GL_NORMAL_ARRAY_STRIDE = 0x807F;
        public const int GL_NORMAL_ARRAY_TYPE = 0x807E;
        public const int GL_NORMAL_MAP = 0x8511;
        public const int GL_NOTEQUAL = 0x205;
        public const int GL_NO_ERROR = 0x00;
        public const int GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2;
        public const int GL_NUM_EXTENSIONS = 0x821D;
        public const int GL_OBJECT_LINEAR = 0x2401;
        public const int GL_OBJECT_PLANE = 0x2501;
        public const int GL_ONE = 0x01;
        public const int GL_ONE_MINUS_CONSTANT_ALPHA = 0x8004;
        public const int GL_ONE_MINUS_CONSTANT_COLOR = 0x8002;
        public const int GL_ONE_MINUS_DST_ALPHA = 0x305;
        public const int GL_ONE_MINUS_DST_COLOR = 0x307;
        public const int GL_ONE_MINUS_SRC_ALPHA = 0x303;
        public const int GL_ONE_MINUS_SRC_COLOR = 0x301;
        public const int GL_OPERAND0_ALPHA = 0x8598;
        public const int GL_OPERAND0_RGB = 0x8590;
        public const int GL_OPERAND1_ALPHA = 0x8599;
        public const int GL_OPERAND1_RGB = 0x8591;
        public const int GL_OPERAND2_ALPHA = 0x859A;
        public const int GL_OPERAND2_RGB = 0x8592;
        public const int GL_OR = 0x1507;
        public const int GL_ORDER = 0xA01;
        public const int GL_OR_INVERTED = 0x150D;
        public const int GL_OR_REVERSE = 0x150B;
        public const int GL_OUT_OF_MEMORY = 0x505;
        public const int GL_PACK_ALIGNMENT = 0xD05;
        public const int GL_PACK_IMAGE_HEIGHT = 0x806C;
        public const int GL_PACK_LSB_FIRST = 0xD01;
        public const int GL_PACK_ROW_LENGTH = 0xD02;
        public const int GL_PACK_SKIP_IMAGES = 0x806B;
        public const int GL_PACK_SKIP_PIXELS = 0xD04;
        public const int GL_PACK_SKIP_ROWS = 0xD03;
        public const int GL_PACK_SWAP_BYTES = 0xD00;
        public const int GL_PASS_THROUGH_TOKEN = 0x700;
        public const int GL_PERSPECTIVE_CORRECTION_HINT = 0xC50;
        public const int GL_PIXEL_MAP_A_TO_A = 0xC79;
        public const int GL_PIXEL_MAP_A_TO_A_SIZE = 0xCB9;
        public const int GL_PIXEL_MAP_B_TO_B = 0xC78;
        public const int GL_PIXEL_MAP_B_TO_B_SIZE = 0xCB8;
        public const int GL_PIXEL_MAP_G_TO_G = 0xC77;
        public const int GL_PIXEL_MAP_G_TO_G_SIZE = 0xCB7;
        public const int GL_PIXEL_MAP_I_TO_A = 0xC75;
        public const int GL_PIXEL_MAP_I_TO_A_SIZE = 0xCB5;
        public const int GL_PIXEL_MAP_I_TO_B = 0xC74;
        public const int GL_PIXEL_MAP_I_TO_B_SIZE = 0xCB4;
        public const int GL_PIXEL_MAP_I_TO_G = 0xC73;
        public const int GL_PIXEL_MAP_I_TO_G_SIZE = 0xCB3;
        public const int GL_PIXEL_MAP_I_TO_I = 0xC70;
        public const int GL_PIXEL_MAP_I_TO_I_SIZE = 0xCB0;
        public const int GL_PIXEL_MAP_I_TO_R = 0xC72;
        public const int GL_PIXEL_MAP_I_TO_R_SIZE = 0xCB2;
        public const int GL_PIXEL_MAP_R_TO_R = 0xC76;
        public const int GL_PIXEL_MAP_R_TO_R_SIZE = 0xCB6;
        public const int GL_PIXEL_MAP_S_TO_S = 0xC71;
        public const int GL_PIXEL_MAP_S_TO_S_SIZE = 0xCB1;
        public const int GL_PIXEL_MODE_BIT = 0x20;
        public const int GL_PIXEL_PACK_BUFFER = 0x88EB;
        public const int GL_PIXEL_PACK_BUFFER_BINDING = 0x88ED;
        public const int GL_PIXEL_UNPACK_BUFFER = 0x88EC;
        public const int GL_PIXEL_UNPACK_BUFFER_BINDING = 0x88EF;
        public const int GL_POINT = 0x1B00;
        public const int GL_POINTS = 0x00;
        public const int GL_POINT_BIT = 0x02;
        public const int GL_POINT_DISTANCE_ATTENUATION = 0x8129;
        public const int GL_POINT_FADE_THRESHOLD_SIZE = 0x8128;
        public const int GL_POINT_SIZE = 0xB11;
        public const int GL_POINT_SIZE_GRANULARITY = 0xB13;
        public const int GL_POINT_SIZE_MAX = 0x8127;
        public const int GL_POINT_SIZE_MIN = 0x8126;
        public const int GL_POINT_SIZE_RANGE = 0xB12;
        public const int GL_POINT_SMOOTH = 0xB10;
        public const int GL_POINT_SMOOTH_HINT = 0xC51;
        public const int GL_POINT_SPRITE = 0x8861;
        public const int GL_POINT_SPRITE_COORD_ORIGIN = 0x8CA0;
        public const int GL_POINT_TOKEN = 0x701;
        public const int GL_POLYGON = 0x09;
        public const int GL_POLYGON_BIT = 0x08;
        public const int GL_POLYGON_MODE = 0xB40;
        public const int GL_POLYGON_OFFSET_FACTOR = 0x8038;
        public const int GL_POLYGON_OFFSET_FILL = 0x8037;
        public const int GL_POLYGON_OFFSET_LINE = 0x2A02;
        public const int GL_POLYGON_OFFSET_POINT = 0x2A01;
        public const int GL_POLYGON_OFFSET_UNITS = 0x2A00;
        public const int GL_POLYGON_SMOOTH = 0xB41;
        public const int GL_POLYGON_SMOOTH_HINT = 0xC53;
        public const int GL_POLYGON_STIPPLE = 0xB42;
        public const int GL_POLYGON_STIPPLE_BIT = 0x10;
        public const int GL_POLYGON_TOKEN = 0x703;
        public const int GL_POSITION = 0x1203;
        public const int GL_PREVIOUS = 0x8578;
        public const int GL_PRIMARY_COLOR = 0x8577;
        public const int GL_PRIMITIVES_GENERATED = 0x8C87;
        public const int GL_PRIMITIVE_RESTART = 0x8F9D;
        public const int GL_PRIMITIVE_RESTART_INDEX = 0x8F9E;
        public const int GL_PROJECTION = 0x1701;
        public const int GL_PROJECTION_MATRIX = 0xBA7;
        public const int GL_PROJECTION_STACK_DEPTH = 0xBA4;
        public const int GL_PROXY_TEXTURE_1D = 0x8063;
        public const int GL_PROXY_TEXTURE_1D_ARRAY = 0x8C19;
        public const int GL_PROXY_TEXTURE_2D = 0x8064;
        public const int GL_PROXY_TEXTURE_2D_ARRAY = 0x8C1B;
        public const int GL_PROXY_TEXTURE_3D = 0x8070;
        public const int GL_PROXY_TEXTURE_CUBE_MAP = 0x851B;
        public const int GL_PROXY_TEXTURE_RECTANGLE = 0x84F7;
        public const int GL_Q = 0x2003;
        public const int GL_QUADRATIC_ATTENUATION = 0x1209;
        public const int GL_QUADS = 0x07;
        public const int GL_QUAD_STRIP = 0x08;
        public const int GL_QUERY_BY_REGION_NO_WAIT = 0x8E16;
        public const int GL_QUERY_BY_REGION_WAIT = 0x8E15;
        public const int GL_QUERY_COUNTER_BITS = 0x8864;
        public const int GL_QUERY_NO_WAIT = 0x8E14;
        public const int GL_QUERY_RESULT = 0x8866;
        public const int GL_QUERY_RESULT_AVAILABLE = 0x8867;
        public const int GL_QUERY_WAIT = 0x8E13;
        public const int GL_R = 0x2002;
        public const int GL_R11F_G11F_B10F = 0x8C3A;
        public const int GL_R16 = 0x822A;
        public const int GL_R16F = 0x822D;
        public const int GL_R16I = 0x8233;
        public const int GL_R16UI = 0x8234;
        public const int GL_R16_SNORM = 0x8F98;
        public const int GL_R32F = 0x822E;
        public const int GL_R32I = 0x8235;
        public const int GL_R32UI = 0x8236;
        public const int GL_R3_G3_B2 = 0x2A10;
        public const int GL_R8 = 0x8229;
        public const int GL_R8I = 0x8231;
        public const int GL_R8UI = 0x8232;
        public const int GL_R8_SNORM = 0x8F94;
        public const int GL_RASTERIZER_DISCARD = 0x8C89;
        public const int GL_READ_BUFFER = 0xC02;
        public const int GL_READ_FRAMEBUFFER = 0x8CA8;
        public const int GL_READ_FRAMEBUFFER_BINDING = 0x8CAA;
        public const int GL_READ_ONLY = 0x88B8;
        public const int GL_READ_WRITE = 0x88BA;
        public const int GL_RED = 0x1903;
        public const int GL_RED_BIAS = 0xD15;
        public const int GL_RED_BITS = 0xD52;
        public const int GL_RED_INTEGER = 0x8D94;
        public const int GL_RED_SCALE = 0xD14;
        public const int GL_RED_SNORM = 0x8F90;
        public const int GL_REFLECTION_MAP = 0x8512;
        public const int GL_RENDER = 0x1C00;
        public const int GL_RENDERBUFFER = 0x8D41;
        public const int GL_RENDERBUFFER_ALPHA_SIZE = 0x8D53;
        public const int GL_RENDERBUFFER_BINDING = 0x8CA7;
        public const int GL_RENDERBUFFER_BLUE_SIZE = 0x8D52;
        public const int GL_RENDERBUFFER_DEPTH_SIZE = 0x8D54;
        public const int GL_RENDERBUFFER_GREEN_SIZE = 0x8D51;
        public const int GL_RENDERBUFFER_HEIGHT = 0x8D43;
        public const int GL_RENDERBUFFER_INTERNAL_FORMAT = 0x8D44;
        public const int GL_RENDERBUFFER_RED_SIZE = 0x8D50;
        public const int GL_RENDERBUFFER_SAMPLES = 0x8CAB;
        public const int GL_RENDERBUFFER_STENCIL_SIZE = 0x8D55;
        public const int GL_RENDERBUFFER_WIDTH = 0x8D42;
        public const int GL_RENDERER = 0x1F01;
        public const int GL_RENDER_MODE = 0xC40;
        public const int GL_REPEAT = 0x2901;
        public const int GL_REPLACE = 0x1E01;
        public const int GL_RESCALE_NORMAL = 0x803A;
        public const int GL_RETURN = 0x102;
        public const int GL_RG = 0x8227;
        public const int GL_RG16 = 0x822C;
        public const int GL_RG16F = 0x822F;
        public const int GL_RG16I = 0x8239;
        public const int GL_RG16UI = 0x823A;
        public const int GL_RG16_SNORM = 0x8F99;
        public const int GL_RG32F = 0x8230;
        public const int GL_RG32I = 0x823B;
        public const int GL_RG32UI = 0x823C;
        public const int GL_RG8 = 0x822B;
        public const int GL_RG8I = 0x8237;
        public const int GL_RG8UI = 0x8238;
        public const int GL_RG8_SNORM = 0x8F95;
        public const int GL_RGB = 0x1907;
        public const int GL_RGB10 = 0x8052;
        public const int GL_RGB10_A2 = 0x8059;
        public const int GL_RGB12 = 0x8053;
        public const int GL_RGB16 = 0x8054;
        public const int GL_RGB16F = 0x881B;
        public const int GL_RGB16I = 0x8D89;
        public const int GL_RGB16UI = 0x8D77;
        public const int GL_RGB16_SNORM = 0x8F9A;
        public const int GL_RGB32F = 0x8815;
        public const int GL_RGB32I = 0x8D83;
        public const int GL_RGB32UI = 0x8D71;
        public const int GL_RGB4 = 0x804F;
        public const int GL_RGB5 = 0x8050;
        public const int GL_RGB5_A1 = 0x8057;
        public const int GL_RGB8 = 0x8051;
        public const int GL_RGB8I = 0x8D8F;
        public const int GL_RGB8UI = 0x8D7D;
        public const int GL_RGB8_SNORM = 0x8F96;
        public const int GL_RGB9_E5 = 0x8C3D;
        public const int GL_RGBA = 0x1908;
        public const int GL_RGBA12 = 0x805A;
        public const int GL_RGBA16 = 0x805B;
        public const int GL_RGBA16F = 0x881A;
        public const int GL_RGBA16I = 0x8D88;
        public const int GL_RGBA16UI = 0x8D76;
        public const int GL_RGBA16_SNORM = 0x8F9B;
        public const int GL_RGBA2 = 0x8055;
        public const int GL_RGBA32F = 0x8814;
        public const int GL_RGBA32I = 0x8D82;
        public const int GL_RGBA32UI = 0x8D70;
        public const int GL_RGBA4 = 0x8056;
        public const int GL_RGBA8 = 0x8058;
        public const int GL_RGBA8I = 0x8D8E;
        public const int GL_RGBA8UI = 0x8D7C;
        public const int GL_RGBA8_SNORM = 0x8F97;
        public const int GL_RGBA_INTEGER = 0x8D99;
        public const int GL_RGBA_INTEGER_MODE = 0x8D9E;
        public const int GL_RGBA_MODE = 0xC31;
        public const int GL_RGBA_SNORM = 0x8F93;
        public const int GL_RGB_INTEGER = 0x8D98;
        public const int GL_RGB_SCALE = 0x8573;
        public const int GL_RGB_SNORM = 0x8F92;
        public const int GL_RG_INTEGER = 0x8228;
        public const int GL_RG_SNORM = 0x8F91;
        public const int GL_RIGHT = 0x407;
        public const int GL_S = 0x2000;
        public const int GL_SAMPLER_1D = 0x8B5D;
        public const int GL_SAMPLER_1D_ARRAY = 0x8DC0;
        public const int GL_SAMPLER_1D_ARRAY_SHADOW = 0x8DC3;
        public const int GL_SAMPLER_1D_SHADOW = 0x8B61;
        public const int GL_SAMPLER_2D = 0x8B5E;
        public const int GL_SAMPLER_2D_ARRAY = 0x8DC1;
        public const int GL_SAMPLER_2D_ARRAY_SHADOW = 0x8DC4;
        public const int GL_SAMPLER_2D_RECT = 0x8B63;
        public const int GL_SAMPLER_2D_RECT_SHADOW = 0x8B64;
        public const int GL_SAMPLER_2D_SHADOW = 0x8B62;
        public const int GL_SAMPLER_3D = 0x8B5F;
        public const int GL_SAMPLER_BUFFER = 0x8DC2;
        public const int GL_SAMPLER_CUBE = 0x8B60;
        public const int GL_SAMPLER_CUBE_SHADOW = 0x8DC5;
        public const int GL_SAMPLES = 0x80A9;
        public const int GL_SAMPLES_PASSED = 0x8914;
        public const int GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E;
        public const int GL_SAMPLE_ALPHA_TO_ONE = 0x809F;
        public const int GL_SAMPLE_BUFFERS = 0x80A8;
        public const int GL_SAMPLE_COVERAGE = 0x80A0;
        public const int GL_SAMPLE_COVERAGE_INVERT = 0x80AB;
        public const int GL_SAMPLE_COVERAGE_VALUE = 0x80AA;
        public const int GL_SCISSOR_BIT = 0x80000;
        public const int GL_SCISSOR_BOX = 0xC10;
        public const int GL_SCISSOR_TEST = 0xC11;
        public const int GL_SECONDARY_COLOR_ARRAY = 0x845E;
        public const int GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING = 0x889C;
        public const int GL_SECONDARY_COLOR_ARRAY_POINTER = 0x845D;
        public const int GL_SECONDARY_COLOR_ARRAY_SIZE = 0x845A;
        public const int GL_SECONDARY_COLOR_ARRAY_STRIDE = 0x845C;
        public const int GL_SECONDARY_COLOR_ARRAY_TYPE = 0x845B;
        public const int GL_SELECT = 0x1C02;
        public const int GL_SELECTION_BUFFER_POINTER = 0xDF3;
        public const int GL_SELECTION_BUFFER_SIZE = 0xDF4;
        public const int GL_SEPARATE_ATTRIBS = 0x8C8D;
        public const int GL_SEPARATE_SPECULAR_COLOR = 0x81FA;
        public const int GL_SET = 0x150F;
        public const int GL_SHADER_OBJECT = 0x8B48;
        public const int GL_SHADER_SOURCE_LENGTH = 0x8B88;
        public const int GL_SHADER_TYPE = 0x8B4F;
        public const int GL_SHADE_MODEL = 0xB54;
        public const int GL_SHININESS = 0x1601;
        public const int GL_SHORT = 0x1402;
        public const int GL_SIGNED_NORMALIZED = 0x8F9C;
        public const int GL_SINGLE_COLOR = 0x81F9;
        public const int GL_SLUMINANCE = 0x8C46;
        public const int GL_SLUMINANCE8 = 0x8C47;
        public const int GL_SLUMINANCE8_ALPHA8 = 0x8C45;
        public const int GL_SLUMINANCE_ALPHA = 0x8C44;
        public const int GL_SMOOTH = 0x1D01;
        public const int GL_SMOOTH_LINE_WIDTH_GRANULARITY = 0xB23;
        public const int GL_SMOOTH_LINE_WIDTH_RANGE = 0xB22;
        public const int GL_SMOOTH_POINT_SIZE_GRANULARITY = 0xB13;
        public const int GL_SMOOTH_POINT_SIZE_RANGE = 0xB12;
        public const int GL_SOURCE0_ALPHA = 0x8588;
        public const int GL_SOURCE0_RGB = 0x8580;
        public const int GL_SOURCE1_ALPHA = 0x8589;
        public const int GL_SOURCE1_RGB = 0x8581;
        public const int GL_SOURCE2_ALPHA = 0x858A;
        public const int GL_SOURCE2_RGB = 0x8582;
        public const int GL_SPECULAR = 0x1202;
        public const int GL_SPHERE_MAP = 0x2402;
        public const int GL_SPOT_CUTOFF = 0x1206;
        public const int GL_SPOT_DIRECTION = 0x1204;
        public const int GL_SPOT_EXPONENT = 0x1205;
        public const int GL_SRC0_ALPHA = 0x8588;
        public const int GL_SRC0_RGB = 0x8580;
        public const int GL_SRC1_ALPHA = 0x8589;
        public const int GL_SRC1_RGB = 0x8581;
        public const int GL_SRC2_ALPHA = 0x858A;
        public const int GL_SRC2_RGB = 0x8582;
        public const int GL_SRC_ALPHA = 0x302;
        public const int GL_SRC_ALPHA_SATURATE = 0x308;
        public const int GL_SRC_COLOR = 0x300;
        public const int GL_SRGB = 0x8C40;
        public const int GL_SRGB8 = 0x8C41;
        public const int GL_SRGB8_ALPHA8 = 0x8C43;
        public const int GL_SRGB_ALPHA = 0x8C42;
        public const int GL_STACK_OVERFLOW = 0x503;
        public const int GL_STACK_UNDERFLOW = 0x504;
        public const int GL_STATIC_COPY = 0x88E6;
        public const int GL_STATIC_DRAW = 0x88E4;
        public const int GL_STATIC_READ = 0x88E5;
        public const int GL_STENCIL = 0x1802;
        public const int GL_STENCIL_ATTACHMENT = 0x8D20;
        public const int GL_STENCIL_BACK_FAIL = 0x8801;
        public const int GL_STENCIL_BACK_FUNC = 0x8800;
        public const int GL_STENCIL_BACK_PASS_DEPTH_FAIL = 0x8802;
        public const int GL_STENCIL_BACK_PASS_DEPTH_PASS = 0x8803;
        public const int GL_STENCIL_BACK_REF = 0x8CA3;
        public const int GL_STENCIL_BACK_VALUE_MASK = 0x8CA4;
        public const int GL_STENCIL_BACK_WRITEMASK = 0x8CA5;
        public const int GL_STENCIL_BITS = 0xD57;
        public const int GL_STENCIL_BUFFER = 0x8224;
        public const int GL_STENCIL_BUFFER_BIT = 0x400;
        public const int GL_STENCIL_CLEAR_VALUE = 0xB91;
        public const int GL_STENCIL_FAIL = 0xB94;
        public const int GL_STENCIL_FUNC = 0xB92;
        public const int GL_STENCIL_INDEX = 0x1901;
        public const int GL_STENCIL_INDEX1 = 0x8D46;
        public const int GL_STENCIL_INDEX16 = 0x8D49;
        public const int GL_STENCIL_INDEX4 = 0x8D47;
        public const int GL_STENCIL_INDEX8 = 0x8D48;
        public const int GL_STENCIL_PASS_DEPTH_FAIL = 0xB95;
        public const int GL_STENCIL_PASS_DEPTH_PASS = 0xB96;
        public const int GL_STENCIL_REF = 0xB97;
        public const int GL_STENCIL_TEST = 0xB90;
        public const int GL_STENCIL_VALUE_MASK = 0xB93;
        public const int GL_STENCIL_WRITEMASK = 0xB98;
        public const int GL_STEREO = 0xC33;
        public const int GL_STREAM_COPY = 0x88E2;
        public const int GL_STREAM_DRAW = 0x88E0;
        public const int GL_STREAM_READ = 0x88E1;
        public const int GL_SUBPIXEL_BITS = 0xD50;
        public const int GL_SUBTRACT = 0x84E7;
        public const int GL_T = 0x2001;
        public const int GL_T2F_C3F_V3F = 0x2A2A;
        public const int GL_T2F_C4F_N3F_V3F = 0x2A2C;
        public const int GL_T2F_C4UB_V3F = 0x2A29;
        public const int GL_T2F_N3F_V3F = 0x2A2B;
        public const int GL_T2F_V3F = 0x2A27;
        public const int GL_T4F_C4F_N3F_V4F = 0x2A2D;
        public const int GL_T4F_V4F = 0x2A28;
        public const int GL_TEXTURE = 0x1702;
        public const int GL_TEXTURE0 = 0x84C0;
        public const int GL_TEXTURE_1D = 0xDE0;
        public const int GL_TEXTURE_1D_ARRAY = 0x8C18;
        public const int GL_TEXTURE_2D = 0xDE1;
        public const int GL_TEXTURE_2D_ARRAY = 0x8C1A;
        public const int GL_TEXTURE_3D = 0x806F;
        public const int GL_TEXTURE_ALPHA_SIZE = 0x805F;
        public const int GL_TEXTURE_ALPHA_TYPE = 0x8C13;
        public const int GL_TEXTURE_BASE_LEVEL = 0x813C;
        public const int GL_TEXTURE_BINDING_1D = 0x8068;
        public const int GL_TEXTURE_BINDING_1D_ARRAY = 0x8C1C;
        public const int GL_TEXTURE_BINDING_2D = 0x8069;
        public const int GL_TEXTURE_BINDING_2D_ARRAY = 0x8C1D;
        public const int GL_TEXTURE_BINDING_3D = 0x806A;
        public const int GL_TEXTURE_BINDING_BUFFER = 0x8C2C;
        public const int GL_TEXTURE_BINDING_CUBE_MAP = 0x8514;
        public const int GL_TEXTURE_BINDING_RECTANGLE = 0x84F6;
        public const int GL_TEXTURE_BIT = 0x40000;
        public const int GL_TEXTURE_BLUE_SIZE = 0x805E;
        public const int GL_TEXTURE_BLUE_TYPE = 0x8C12;
        public const int GL_TEXTURE_BORDER = 0x1005;
        public const int GL_TEXTURE_BORDER_COLOR = 0x1004;
        public const int GL_TEXTURE_BUFFER = 0x8C2A;
        public const int GL_TEXTURE_BUFFER_DATA_STORE_BINDING = 0x8C2D;
        public const int GL_TEXTURE_BUFFER_FORMAT = 0x8C2E;
        public const int GL_TEXTURE_COMPARE_FUNC = 0x884D;
        public const int GL_TEXTURE_COMPARE_MODE = 0x884C;
        public const int GL_TEXTURE_COMPONENTS = 0x1003;
        public const int GL_TEXTURE_COMPRESSED = 0x86A1;
        public const int GL_TEXTURE_COMPRESSED_IMAGE_SIZE = 0x86A0;
        public const int GL_TEXTURE_COMPRESSION_HINT = 0x84EF;
        public const int GL_TEXTURE_COORD_ARRAY = 0x8078;
        public const int GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING = 0x889A;
        public const int GL_TEXTURE_COORD_ARRAY_POINTER = 0x8092;
        public const int GL_TEXTURE_COORD_ARRAY_SIZE = 0x8088;
        public const int GL_TEXTURE_COORD_ARRAY_STRIDE = 0x808A;
        public const int GL_TEXTURE_COORD_ARRAY_TYPE = 0x8089;
        public const int GL_TEXTURE_CUBE_MAP = 0x8513;
        public const int GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 0x8516;
        public const int GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x8518;
        public const int GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x851A;
        public const int GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0x8515;
        public const int GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 0x8517;
        public const int GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 0x8519;
        public const int GL_TEXTURE_DEPTH = 0x8071;
        public const int GL_TEXTURE_DEPTH_SIZE = 0x884A;
        public const int GL_TEXTURE_DEPTH_TYPE = 0x8C16;
        public const int GL_TEXTURE_ENV = 0x2300;
        public const int GL_TEXTURE_ENV_COLOR = 0x2201;
        public const int GL_TEXTURE_ENV_MODE = 0x2200;
        public const int GL_TEXTURE_FILTER_CONTROL = 0x8500;
        public const int GL_TEXTURE_GEN_MODE = 0x2500;
        public const int GL_TEXTURE_GEN_Q = 0xC63;
        public const int GL_TEXTURE_GEN_R = 0xC62;
        public const int GL_TEXTURE_GEN_S = 0xC60;
        public const int GL_TEXTURE_GEN_T = 0xC61;
        public const int GL_TEXTURE_GREEN_SIZE = 0x805D;
        public const int GL_TEXTURE_GREEN_TYPE = 0x8C11;
        public const int GL_TEXTURE_HEIGHT = 0x1001;
        public const int GL_TEXTURE_INTENSITY_SIZE = 0x8061;
        public const int GL_TEXTURE_INTENSITY_TYPE = 0x8C15;
        public const int GL_TEXTURE_INTERNAL_FORMAT = 0x1003;
        public const int GL_TEXTURE_LOD_BIAS = 0x8501;
        public const int GL_TEXTURE_LUMINANCE_SIZE = 0x8060;
        public const int GL_TEXTURE_LUMINANCE_TYPE = 0x8C14;
        public const int GL_TEXTURE_MAG_FILTER = 0x2800;
        public const int GL_TEXTURE_MATRIX = 0xBA8;
        public const int GL_TEXTURE_MAX_LEVEL = 0x813D;
        public const int GL_TEXTURE_MAX_LOD = 0x813B;
        public const int GL_TEXTURE_MIN_FILTER = 0x2801;
        public const int GL_TEXTURE_MIN_LOD = 0x813A;
        public const int GL_TEXTURE_PRIORITY = 0x8066;
        public const int GL_TEXTURE_RECTANGLE = 0x84F5;
        public const int GL_TEXTURE_RED_SIZE = 0x805C;
        public const int GL_TEXTURE_RED_TYPE = 0x8C10;
        public const int GL_TEXTURE_RESIDENT = 0x8067;
        public const int GL_TEXTURE_SHARED_SIZE = 0x8C3F;
        public const int GL_TEXTURE_STACK_DEPTH = 0xBA5;
        public const int GL_TEXTURE_STENCIL_SIZE = 0x88F1;
        public const int GL_TEXTURE_WIDTH = 0x1000;
        public const int GL_TEXTURE_WRAP_R = 0x8072;
        public const int GL_TEXTURE_WRAP_S = 0x2802;
        public const int GL_TEXTURE_WRAP_T = 0x2803;
        public const int GL_TRANSFORM_BIT = 0x1000;
        public const int GL_TRANSFORM_FEEDBACK_BUFFER = 0x8C8E;
        public const int GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = 0x8C8F;
        public const int GL_TRANSFORM_FEEDBACK_BUFFER_MODE = 0x8C7F;
        public const int GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = 0x8C85;
        public const int GL_TRANSFORM_FEEDBACK_BUFFER_START = 0x8C84;
        public const int GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 0x8C88;
        public const int GL_TRANSFORM_FEEDBACK_VARYINGS = 0x8C83;
        public const int GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = 0x8C76;
        public const int GL_TRANSPOSE_COLOR_MATRIX = 0x84E6;
        public const int GL_TRANSPOSE_MODELVIEW_MATRIX = 0x84E3;
        public const int GL_TRANSPOSE_PROJECTION_MATRIX = 0x84E4;
        public const int GL_TRANSPOSE_TEXTURE_MATRIX = 0x84E5;
        public const int GL_TRIANGLES = 0x04;
        public const int GL_TRIANGLE_FAN = 0x06;
        public const int GL_TRIANGLE_STRIP = 0x05;
        public const int GL_TRUE = 0x01;
        public const int GL_UNIFORM_ARRAY_STRIDE = 0x8A3C;
        public const int GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS = 0x8A42;
        public const int GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = 0x8A43;
        public const int GL_UNIFORM_BLOCK_BINDING = 0x8A3F;
        public const int GL_UNIFORM_BLOCK_DATA_SIZE = 0x8A40;
        public const int GL_UNIFORM_BLOCK_INDEX = 0x8A3A;
        public const int GL_UNIFORM_BLOCK_NAME_LENGTH = 0x8A41;
        public const int GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = 0x8A46;
        public const int GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER = 0x8A45;
        public const int GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = 0x8A44;
        public const int GL_UNIFORM_BUFFER = 0x8A11;
        public const int GL_UNIFORM_BUFFER_BINDING = 0x8A28;
        public const int GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 0x8A34;
        public const int GL_UNIFORM_BUFFER_SIZE = 0x8A2A;
        public const int GL_UNIFORM_BUFFER_START = 0x8A29;
        public const int GL_UNIFORM_IS_ROW_MAJOR = 0x8A3E;
        public const int GL_UNIFORM_MATRIX_STRIDE = 0x8A3D;
        public const int GL_UNIFORM_NAME_LENGTH = 0x8A39;
        public const int GL_UNIFORM_OFFSET = 0x8A3B;
        public const int GL_UNIFORM_SIZE = 0x8A38;
        public const int GL_UNIFORM_TYPE = 0x8A37;
        public const int GL_UNPACK_ALIGNMENT = 0xCF5;
        public const int GL_UNPACK_IMAGE_HEIGHT = 0x806E;
        public const int GL_UNPACK_LSB_FIRST = 0xCF1;
        public const int GL_UNPACK_ROW_LENGTH = 0xCF2;
        public const int GL_UNPACK_SKIP_IMAGES = 0x806D;
        public const int GL_UNPACK_SKIP_PIXELS = 0xCF4;
        public const int GL_UNPACK_SKIP_ROWS = 0xCF3;
        public const int GL_UNPACK_SWAP_BYTES = 0xCF0;
        public const int GL_UNSIGNED_BYTE = 0x1401;
        public const int GL_UNSIGNED_BYTE_2_3_3_REV = 0x8362;
        public const int GL_UNSIGNED_BYTE_3_3_2 = 0x8032;
        public const int GL_UNSIGNED_INT = 0x1405;
        public const int GL_UNSIGNED_INT_10F_11F_11F_REV = 0x8C3B;
        public const int GL_UNSIGNED_INT_10_10_10_2 = 0x8036;
        public const int GL_UNSIGNED_INT_24_8 = 0x84FA;
        public const int GL_UNSIGNED_INT_2_10_10_10_REV = 0x8368;
        public const int GL_UNSIGNED_INT_5_9_9_9_REV = 0x8C3E;
        public const int GL_UNSIGNED_INT_8_8_8_8 = 0x8035;
        public const int GL_UNSIGNED_INT_8_8_8_8_REV = 0x8367;
        public const int GL_UNSIGNED_INT_SAMPLER_1D = 0x8DD1;
        public const int GL_UNSIGNED_INT_SAMPLER_1D_ARRAY = 0x8DD6;
        public const int GL_UNSIGNED_INT_SAMPLER_2D = 0x8DD2;
        public const int GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = 0x8DD7;
        public const int GL_UNSIGNED_INT_SAMPLER_2D_RECT = 0x8DD5;
        public const int GL_UNSIGNED_INT_SAMPLER_3D = 0x8DD3;
        public const int GL_UNSIGNED_INT_SAMPLER_BUFFER = 0x8DD8;
        public const int GL_UNSIGNED_INT_SAMPLER_CUBE = 0x8DD4;
        public const int GL_UNSIGNED_INT_VEC2 = 0x8DC6;
        public const int GL_UNSIGNED_INT_VEC3 = 0x8DC7;
        public const int GL_UNSIGNED_INT_VEC4 = 0x8DC8;
        public const int GL_UNSIGNED_NORMALIZED = 0x8C17;
        public const int GL_UNSIGNED_SHORT = 0x1403;
        public const int GL_UNSIGNED_SHORT_1_5_5_5_REV = 0x8366;
        public const int GL_UNSIGNED_SHORT_4_4_4_4 = 0x8033;
        public const int GL_UNSIGNED_SHORT_4_4_4_4_REV = 0x8365;
        public const int GL_UNSIGNED_SHORT_5_5_5_1 = 0x8034;
        public const int GL_UNSIGNED_SHORT_5_6_5 = 0x8363;
        public const int GL_UNSIGNED_SHORT_5_6_5_REV = 0x8364;
        public const int GL_UPPER_LEFT = 0x8CA2;
        public const int GL_V2F = 0x2A20;
        public const int GL_V3F = 0x2A21;
        public const int GL_VALIDATE_STATUS = 0x8B83;
        public const int GL_VENDOR = 0x1F00;
        public const int GL_VERSION = 0x1F02;
        public const int GL_VERTEX_ARRAY = 0x8074;
        public const int GL_VERTEX_ARRAY_BINDING = 0x85B5;
        public const int GL_VERTEX_ARRAY_BUFFER_BINDING = 0x8896;
        public const int GL_VERTEX_ARRAY_POINTER = 0x808E;
        public const int GL_VERTEX_ARRAY_SIZE = 0x807A;
        public const int GL_VERTEX_ARRAY_STRIDE = 0x807C;
        public const int GL_VERTEX_ARRAY_TYPE = 0x807B;
        public const int GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 0x889F;
        public const int GL_VERTEX_ATTRIB_ARRAY_ENABLED = 0x8622;
        public const int GL_VERTEX_ATTRIB_ARRAY_INTEGER = 0x88FD;
        public const int GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = 0x886A;
        public const int GL_VERTEX_ATTRIB_ARRAY_POINTER = 0x8645;
        public const int GL_VERTEX_ATTRIB_ARRAY_SIZE = 0x8623;
        public const int GL_VERTEX_ATTRIB_ARRAY_STRIDE = 0x8624;
        public const int GL_VERTEX_ATTRIB_ARRAY_TYPE = 0x8625;
        public const int GL_VERTEX_PROGRAM_POINT_SIZE = 0x8642;
        public const int GL_VERTEX_PROGRAM_TWO_SIDE = 0x8643;
        public const int GL_VERTEX_SHADER = 0x8B31;
        public const int GL_VIEWPORT = 0xBA2;
        public const int GL_VIEWPORT_BIT = 0x800;
        public const int GL_WEIGHT_ARRAY_BUFFER_BINDING = 0x889E;
        public const int GL_WRITE_ONLY = 0x88B9;
        public const int GL_XOR = 0x1506;
        public const int GL_ZERO = 0x00;
        public const int GL_ZOOM_X = 0xD16;
        public const int GL_ZOOM_Y = 0xD17;
        #endregion
    }
}
